image: python:3.10


before_script:
  - python -V # Print out python version for debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt

test-example:
  script:
    - pip install pytest
    - pwd
    - python -m pytest -vvv tests
    


